# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppNormals <- function(n) {
    .Call('OneDayOneRcpp_rcppNormals', PACKAGE = 'OneDayOneRcpp', n)
}

#' @export
#' @param n 测试下中文呢
#' @title boostNormals 
#' @name boostNormals 
boostNormals <- function(n) {
    .Call('OneDayOneRcpp_boostNormals', PACKAGE = 'OneDayOneRcpp', n)
}

#' @export
#' @param n
#' @param seed default value is 42
#' @title cxx11Normal
#' @name cxx11Normal
cxx11Normals <- function(n, seed = 42L) {
    .Call('OneDayOneRcpp_cxx11Normals', PACKAGE = 'OneDayOneRcpp', n, seed)
}

rcpp_hello_world <- function() {
    .Call('OneDayOneRcpp_rcpp_hello_world', PACKAGE = 'OneDayOneRcpp')
}

#' @export
#' @title 测试cpp中的lamda
#' @name lamda
#' @param x 需要转化的函数
transformEx <- function(x) {
    .Call('OneDayOneRcpp_transformEx', PACKAGE = 'OneDayOneRcpp', x)
}

#' @export
parallelJsDistance <- function(mat) {
    .Call('OneDayOneRcpp_parallelJsDistance', PACKAGE = 'OneDayOneRcpp', mat)
}

split_indices <- function(x, n = 0L) {
    .Call('OneDayOneRcpp_split_indices', PACKAGE = 'OneDayOneRcpp', x, n)
}

#' @export
#' @name innerProduct
#' @title 内积的cpp版本
#' @param x 向量x
#' @param y 向量y
innerProduct <- function(x, y) {
    .Call('OneDayOneRcpp_innerProduct', PACKAGE = 'OneDayOneRcpp', x, y)
}

#' @export
#' @title 内积的并行版本
#' @param x,向量x
#' @param y,向量y
#' @name parallelInnerProduct
parallelInnerProduct <- function(x, y) {
    .Call('OneDayOneRcpp_parallelInnerProduct', PACKAGE = 'OneDayOneRcpp', x, y)
}

positives <- function(x) {
    .Call('OneDayOneRcpp_positives', PACKAGE = 'OneDayOneRcpp', x)
}

first_three <- function(x) {
    .Call('OneDayOneRcpp_first_three', PACKAGE = 'OneDayOneRcpp', x)
}

with_names <- function(x, y) {
    .Call('OneDayOneRcpp_with_names', PACKAGE = 'OneDayOneRcpp', x, y)
}

